meta_product_name: "FANTASTIC MISTER ZGUY"
meta_title: "FMZ - Feel Good Indie"
meta_description: "Fantastic, c'est de la feel good indie, où s'entremêlent les émotions."
meta_image: "background.jpg"                           # Une image dans votre dossier app/assets/images/

