meta_product_name: "Fantastic Mister Zguy"
meta_title: "Fantastic Mister Zguy - Feel Good Indie Band"
meta_description: "Fantastic, c'est de la feel good indie, où s'entremêlent les émotions."
meta_image: "background.jpg"                           # Une image dans votre dossier app/assets/images/

